# Generated by Django 5.0.1 on 2025-10-30 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_app', '0002_alter_beneficiary_ration_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rationcard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ration_app.userauth'),
        ),
    ]
